---

homebrew_cask_appdir: /Applications

homebrew_taps:
   - caskroom/cask

homebrew_installed_packages:
  - { name: ccache, state: linked }
  - { name: coreutils, state: linked }
  - { name: doxygen, state: linked }
  - { name: cmake, state: linked }
  - { name: git, state: linked }
  - { name: bash-completion, state: linked }
  - { name: python, state: linked }
  - { name: openssl, state: linked }
  - { name: ssh-copy-id, state: linked }
  - { name: pass, state: linked }
  - { name: wget, state: linked }
