---
- hosts: all
  user: jenkins

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - name: Check if /usr/bin/java is already installed
      stat:
        path: /usr/bin/java
      register: java_state

    - name: Install java
      homebrew_cask: name=java state=present
      when: not java_state.stat.exists

    - name: Copy SSH config files
      copy:
        src=./ssh/{{ item }} dest=/Users/jenkins/.ssh/{{ item }} owner=jenkins group=staff mode=0644
      with_items:
        - authorized_keys
        - id_rsa_factory_macosx-x64-ios-builder
        - known_hosts
