---
- name: Copy {{ item.unattended }}
  win_copy:
    src: "{{ item.unattended }}"
    dest: "C:\\vs-unattended.xml"

- name: Install {{ item.chocopackage }} (takes a long time)
  script: install-vs.ps1 -chocopackage {{ item.chocopackage }}
  register: choco_output
  changed_when: not "already installed" in choco_output.stdout
  failed_when: not "The install of {{ item.chocopackage }} was successful" in choco_output.stdout

- name: Reboot Windows if necessary
  win_reboot:
    shutdown_timeout_sec: 3600
    reboot_timeout_sec: 3600
    when: '"reboot is necessary" in choco_output.stdout'

