---
network_name: "Pool-wide network associated with eth4"
sr_name: "Local storage"
vm_template: "Ubuntu Xenial Xerus 16.04"
install_iso: "ubuntu-18.04-fully-automated.iso"
vm_name: "default_vm"
vcpus: 8
memory: 17179869184
disksize: 210000000000
ansible_password: "{{ cmdline_password }}"