---
- hosts: all
  user: couchbase

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - name: Install java
      homebrew_cask: name=java state=present

    - name: set energy saving to zero
      shell: systemsetup -setcomputersleep Never
      become: true
