version: '3.5'

# Suggested deployment command:
#  docker stack deploy -c sdk-jenkins.yaml sdk
# All services, networks, etc. will then get an "sdk_" prefix,
# eg. "sdk_jenkins"

services:

  # sdk.jenkins.couchbase.com
  jenkins:
    image: couchbasebuild/jenkins:20180123
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /builds/jenkins/sdk-jenkins-home
        target: /var/jenkins_home
    networks:
      - jenkins

# See http://www.technowise.in/2016/10/fix-no-valid-crumb-was-included-in.html
# and https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Nginx
# for the reason behind -Dhudson.security.csrf.requestfield
    environment:
      - "JAVA_OPTS=-Dhudson.security.csrf.requestfield=Jenkins-Crumb"

  centos6:
    image: couchbasebuild/sdk-centos6-build:20180314
    deploy:
      replicas: 1
    networks:
      - jenkins
    environment:
# Due to https://github.com/docker/compose/issues/229, the Jenkins container is
# created with a container name "sdk_jenkins", which is not a valid DNS entry.
# "dig" will actually resolve it OK inside another container, but Java will
# not, so we can't reference eg. "http://sdk_jenkins:8080/" as you would expect.
# However, fortunately the "short" service name (the name from here in this
# compose file) also works, so we use that here for the master URL.
      - "JENKINS_MASTER=http://jenkins:8080/"
      - "JENKINS_SLAVE_NAME=centos6"
      - "JENKINS_SLAVE_LABELS=centos6"
    secrets:
      - source: ns-buildbot.rsa
        target: /home/couchbase/.ssh/ns-buildbot.rsa
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: jenkins_master_username
      - source: jenkins_master_password
    configs:
      - source: jenkins_slave_ssh_config
        target: /home/couchbase/.ssh/config
        uid: '1000'
        gid: '1000'
        mode: 0644

  centos7:
    image: couchbasebuild/sdk-centos7-build:20180314
    deploy:
      replicas: 1
    networks:
      - jenkins
    environment:
      - "JENKINS_MASTER=http://jenkins:8080/"
      - "JENKINS_SLAVE_NAME=centos7"
      - "JENKINS_SLAVE_LABELS=centos7"
    secrets:
      - source: ns-buildbot.rsa
        target: /home/couchbase/.ssh/ns-buildbot.rsa
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: jenkins_master_username
      - source: jenkins_master_password
    configs:
      - source: jenkins_slave_ssh_config
        target: /home/couchbase/.ssh/config
        uid: '1000'
        gid: '1000'
        mode: 0644

  debian8:
    image: couchbasebuild/sdk-debian8-build:20180315
    deploy:
      replicas: 1
    networks:
      - jenkins
    environment:
      - "JENKINS_MASTER=http://jenkins:8080/"
      - "JENKINS_SLAVE_NAME=debian8"
      - "JENKINS_SLAVE_LABELS=debian8"
    secrets:
      - source: ns-buildbot.rsa
        target: /home/couchbase/.ssh/ns-buildbot.rsa
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: jenkins_master_username
      - source: jenkins_master_password
    configs:
      - source: jenkins_slave_ssh_config
        target: /home/couchbase/.ssh/config
        uid: '1000'
        gid: '1000'
        mode: 0644

  ubuntu14:
    image: couchbasebuild/sdk-ubuntu14-build:20180314
    deploy:
      replicas: 1
    networks:
      - jenkins
    environment:
      - "JENKINS_MASTER=http://jenkins:8080/"
      - "JENKINS_SLAVE_NAME=ubuntu14"
      - "JENKINS_SLAVE_LABELS=ubuntu14"
    secrets:
      - source: ns-buildbot.rsa
        target: /home/couchbase/.ssh/ns-buildbot.rsa
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: jenkins_master_username
      - source: jenkins_master_password
    configs:
      - source: jenkins_slave_ssh_config
        target: /home/couchbase/.ssh/config
        uid: '1000'
        gid: '1000'
        mode: 0644

  ubuntu16:
    image: couchbasebuild/sdk-ubuntu16-build:20180314
    deploy:
      replicas: 1
    networks:
      - jenkins
    environment:
      - "JENKINS_MASTER=http://jenkins:8080/"
      - "JENKINS_SLAVE_NAME=ubuntu16"
      - "JENKINS_SLAVE_LABELS=ubuntu16"
    secrets:
      - source: ns-buildbot.rsa
        target: /home/couchbase/.ssh/ns-buildbot.rsa
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: jenkins_master_username
      - source: jenkins_master_password
    configs:
      - source: jenkins_slave_ssh_config
        target: /home/couchbase/.ssh/config
        uid: '1000'
        gid: '1000'
        mode: 0644

secrets:
  # SSH key which can read private GitHub repos
  ns-buildbot.rsa:
    external: true
  jenkins_master_username:
    external: true
  jenkins_master_password:
    external: true

configs:
  jenkins_slave_ssh_config:
    file: conf/jenkins_slave_ssh_config

networks:
  jenkins:
