---
- hosts: all
  gather_facts: no

  tasks:

    - name: win-av-install | Install tools
      win_chocolatey:
        name: "{{ item }}"
        allow_empty_checksums: "yes"
      with_items:
        - clamwin
        - 7zip.commandline
        - jdk8

# Do OpenSSH last so the service has the latest version of the path

    - name: win-av-install | Install OpenSSH (for Jenkins)
      script: openssh.ps1

    - name: win-av-install | Copy SSH config files
      win_copy:
        src: "./ssh/{{ item }}"
        dest: C:\Users\Administrator\.ssh\{{ item }}
      with_items:
        - authorized_keys
        - buildbot_id_dsa
        - config
        - environment
        - id_rsa
        - known_hosts

    - name: win-av-install | Enable Remote Desktop
      win_regedit:
        key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        name: fDenyTSConnections
        data: 0
        type: dword
        state: present

    - name: win-av-install | Open Remote Desktop in firewall
      win_firewall_rule:
        name: "remote desktop"
        enable: yes
        state: present
        localport: 3389
        action: allow
        direction: in
        protocol: TCP
        force: true

